### ISSUE TITLE
If an authenticated user has namedServerLimitPerUser servers you see a generic "Failed to launch image"

### ISSUE THREAD

**Issue by manics** [jupyterhub/binderhub#1022]
```yaml
config:
  BinderHub:
    use_registry: true
    image_prefix: xxx/yyy-
    hub_url_public: http://public.example.org/jupyter/
    hub_url: http://hub:8081/jupyter/
    log_level: 0
    debug: true
    use_named_servers: true
    auth_enabled: true

jupyterhub:
  hub:
    baseUrl: /jupyter/
    redirectToServer: false
    services:
      binder:
        oauth_redirect_uri: "http://public.example.org/oauth_callback"
        oauth_client_id: "binder-oauth-zzz"
    extraConfig:
      binder: |
        from kubespawner import KubeSpawner

        class BinderSpawner(KubeSpawner):

          def start(self):
              if 'image' in self.user_options:
                # binder service sets the image spec via user options
                self.image = self.user_options['image']
              return super().start()

          def get_env(self):
              env = super(BinderSpawner, self).get_env()
              if 'repo_url' in self.user_options:
                  env['BINDER_REPO_URL'] = self.user_options['repo_url']
              for key in (
                      'binder_ref_url',
                      'binder_launch_host',
                      'binder_persistent_request',
                      'binder_request'):
                  if key in self.user_options:
                      env[key.upper()] = self.user_options[key]
              return env

        c.JupyterHub.spawner_class = BinderSpawner
    # Allow up to 2 servers per authenticated user
    allowNamedServers: true
    namedServerLimitPerUser: 2
```

If you already have two servers running you see the generic message
```
Found built image, launching...
Launching server...
Launch attempt 1 failed, retrying...
Launch attempt 2 failed, retrying...
Launch attempt 3 failed, retrying...
Failed to launch image xxx/yyy-zzz:tag
```
which gives the impression there was a problem running the image, and may lead the user to waste time rebuilding the image.

The actual problem is shown in the binderhub logs:
```
    b'{"status": 400, "message": "User test already has the maximum of 2 named servers.  One must be deleted before a new server can be created"}'
```
This should be indicated to the user.
