### ISSUE TITLE
JupyterHub URL not showing up in Binder Badge links

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/binderhub#1034]
## Problem

I have just deployed a fresh, vanilla binderhub using [these docs](https://binderhub.readthedocs.io/en/latest/setup-binderhub.html) but the jupyterhub URL (or IP address) is not being parsed to the Binder form for generating links/badges.

This does not affect builds of binders.

<img width="966" alt="Screenshot 2019-12-18 at 10 58 59" src="https://user-images.githubusercontent.com/44771837/71080720-a15fd280-2185-11ea-9176-5ca1c218b123.png">

## Expected behaviour

The URL (or IP address) for the jupyterhub shows up in the binder form when generating links/badges.

## Config info

Binderhub helm chart version: `0.2.0-059.78bfbcd`

`config.yaml`:

```yaml
config:
  BinderHub:
    use_registry: true
    image_prefix: DOCKERHUB_USERNAME/testhub-dev-
    hub_url: http://51.105.127.89
```

`secret.yaml`:

```yaml
jupyterhub:
  hub:
    services:
      binder:
        apiToken: ###secret###
  proxy:
    secretToken: ###secret###

registry:
  username: DOCKERHUB_USERNAME
  password: ###secret###
```
