### ISSUE TITLE
Docker build triggered every time

### ISSUE THREAD

**Issue by ltetrel** [jupyterhub/binderhub#1073]
Hi everyone and thanks for your work,

So we are using a custom docker registry, running on the same network. Every time I launch the same repository, a build is triggered on the k8s node, even if it was already built before.
Given the [documentation](https://binderhub.readthedocs.io/en/latest/overview.html), if the github repository hash is the same, binderhub should not trigger a new build on the k8s node. It seems like the built image is never found by jupyter hub.

Any thoughts ?

k8s version : `1.17.0`
binderhub version : `v0.2.0-n121.h6d936d7`
`config.yaml`
```
# BinderHub config
config:
  BinderHub:
    hub_url: https://*/jupyter
    use_registry: true
    image_prefix: my-registry.com/${binder-url}-
```

**Comment by betatim** [comment]
It sounds like your BinderHub can't find the image in the registry it is configured to use.

Are there (error) messages in the binder pod logs?

Which steps of https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#preparing-to-install did you follow when you setup your registry?

**Comment by ltetrel** [comment]
Thank you,

So I followed [this](https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#if-you-are-using-a-custom-registry).
My `secrets.yaml` has :
```
jupyterhub:
  hub:
    services:
      binder:
        apiToken: *
  proxy:
    secretToken: *
registry:
  url: "my_registry.com"
  username: "*"
  password: "*"
```

Here are the logs from the binder pod. As you can see, the reference from [my repo](https://github.com/ltetrel/binder-tuto) is indeed cached, but just after a build is triggered..
```
[I 200309 15:27:31 repoproviders:778] Using cached ref for https://api.github.com/repos/ltetrel/binder-tuto/commits/master: dc5e69664f99e22133a6e8dfc247202af5653dd2
[I 200309 15:27:31 build:296] Started build build-ltetrel-2dbinder-2dtuto-f9e17d-dc5e69
[I 200309 15:27:31 build:298] Watching build pod build-ltetrel-2dbinder-2dtuto-f9e17d-dc5e69
[I 200309 15:27:35 build:329] Watching logs of build-ltetrel-2dbinder-2dtuto-f9e17d-dc5e69
[I 200309 15:27:46 builder:496] Launching pod for https://github.com/ltetrel/binder-tuto: 1 other pods running this repo (3 total)
[I 200309 15:27:46 launcher:162] Creating user ltetrel-binder-tuto-nstlp0ew for image binder-registry.conp.cloud/binder.conp.cloud-ltetrel-2dbinder-2dtuto-f9e17d:dc5e69664f99e22133a6e8dfc247202af5653dd2
[I 200309 15:27:46 build:357] Finished streaming logs of build-ltetrel-2dbinder-2dtuto-f9e17d-dc5e69
[I 200309 15:27:47 launcher:209] Starting server for user ltetrel-binder-tuto-nstlp0ew with image binder-registry.conp.cloud/binder.conp.cloud-ltetrel-2dbinder-2dtuto-f9e17d:dc5e69664f99e22133a6e8dfc247202af5653dd2
```
