### ISSUE TITLE
Include timeframe in per-repo custom quotas

### ISSUE THREAD

**Issue by manics** [jupyterhub/binderhub#1138]
### Proposed change
Currently mybinder.org limits the number of concurrent launches for each repo, unless a request has been made and a PR merged. This PR is merged at a suitable time for the new limit to take effect- not too early to prevent excessive load on the cluster, but not too late either!

We could make this less critical by including a timeframe (start/end) on the quota requests.

### Alternative options
Do nothing. Maybe it's OK to just merge the quota PRs as soon as the request is made instead of waiting until the day before?

### Who would use this feature?
mybinder.org admins

### (Optional): Suggest a solution
Current example:
https://github.com/jupyterhub/mybinder.org-deploy/blob/65fc6a56050a56e3e38ea32e54440aad398ae8b3/mybinder/values.yaml#L62-L69

Possible config, the quota is only overridden between the start and end times (iso-8601 UTC)
```yaml
    spec_config:
        - pattern: ^example/example-repo.*
          config:
            quota: 128
            quota_start: 2020-09-01T06:00:00
            quota_end: 2020-09-02T18:00:00
```
