### ISSUE TITLE
Values from binderhub_config.py not applied

### ISSUE THREAD

**Issue by nichoio** [jupyterhub/binderhub#1270]
### Bug description

When providing any values under `config:` for the helm chart, those values appear to be not available in the BinderHub application. I'm building the image for Binderhub myself using `helm-chart/images/binderhub/Dockerfile` which seems to work fine otherwise. However, when putting debug logs into the application deployed to my university cluster, i can see that the values are passed from Helm to binderhub_config.py but not to BinderHub.

Excerpt from `config.yaml`:
```
config:
  BinderHub:
    use_registry: true
    image_prefix: "gitlab.myuni.io/myuni-sys/binderhub"
  DockerRegistry:
    token_url: "https://gitlab.myuni.de/jwt/auth"
    url: "https://gitlab.myuni.io"
```

The file is applied by running `$ helm upgrade binder-demo binderhub/ -f mysecrets.yaml -f config.yaml` from within the helm-chart dir. `print('c: {}'.format(c))` in `binderhub_config.py` shows all these values so it's probably not an issue with helm.

#### Expected behaviour
I would expect that in registry.py and builder.py, attributes such as `self.token_url` and `self.settings['image_prefix']` respectively are identical to what is set in helm under `config:`

#### Actual behaviour
Values such as `self.token_url` and  `self.settings['image_prefix']` are empty.

Kubernetes version: v1.14.7
Local branch is derived from master commit `f5c1a19`
Maybe i'm just misunderstanding something about the way BinderHub is meant to set up. Any help appreciated!
