### ISSUE TITLE
Inspection of started server's containerStatuses to detect errors quickly

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1291]
### Proposed change
To let BinderHub inspect the launched container a bit more intelligently. I can see that a container I've built fail to startup and crashes the same second it starts, but binderhub will wait a long time and then re-attempt two more times and then finally fail after a very long time.

I think it would be nice to add some inspection that concludes if the container has terminated for example and abort the attempt right away when that happens.

This is an example of details about a k8s Pod (`kubectl get pod ... -o yaml`) that errored that binderhub waited for a long time before re-attempting and erroring in the same way.

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-04-22T17:41:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-04-22T17:41:45Z"
    message: 'containers with unready status: [notebook]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-04-22T17:41:45Z"
    message: 'containers with unready status: [notebook]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-04-22T17:41:45Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://042d338aa926b3734ec8ecd8e62254bad797292435cf169c6c4b85b26a6b34e7
    image: gcr.io/binderhub-288415/r2d-staging-72d7634-consideratio-2dtmp-2dbinder-fc2085:2ede134ea9b35ae032230798dc3514fc7dfb15df
    imageID: docker-pullable://gcr.io/binderhub-288415/r2d-staging-72d7634-consideratio-2dtmp-2dbinder-fc2085@sha256:575006011e6ed1225edb8c905fe258a37aed05c8563a4504d52e51a818c84b95
    lastState: {}
    name: notebook
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://042d338aa926b3734ec8ecd8e62254bad797292435cf169c6c4b85b26a6b34e7
        exitCode: 1
        finishedAt: "2021-04-22T17:43:13Z"
        reason: Error
        startedAt: "2021-04-22T17:43:13Z"
```

### Alternative options
No change - accept our current very slow feedback on failure.

### Who would use this feature?
Any person making their repo's binder compatible.

### (Optional): Suggest a solution
I'm not confident yet about the code base, but during the process where binderhub (the python logic) starts a k8s pod it also will monitor and react to obvious failures in k8s. Along with this, one could also collect information if its pulling image or similar which can be nice info to provide the end user.
