### ISSUE TITLE
Can't get eu.gcr.io working on binderhub k8s

### ISSUE THREAD

**Issue by ctr26** [jupyterhub/binderhub#1345]
So I initially attempted the variant in the documentation but my gcloud account is limited to the eu. So I tried the `eu.gcr.io` variants which fail authorisation. The closest I got was having:

```
registry:
  url: https://gcr.io

config:
  BinderHub:
    use_registry: true
    image_prefix: eu.gcr.io/<google-project-id>/<prefix>-
```
Which asked my to got and authorise the service account I was using. But I didn't get much further than that. Has anyone had any success with location restricted `gcr.io`?
