### ISSUE TITLE
Error in cors documentation: missing level in config

### ISSUE THREAD

**Issue by jokuNimi** [jupyterhub/binderhub#1369]
### Bug description
There is an error in the [cors documentation](https://binderhub.readthedocs.io/en/latest/cors.html). It asks me to write 
```
config:
  BinderHub:
    cors_allow_origin: '*'

jupyterhub:
  config:
    BinderSpawner:
      cors_allow_origin: '*'
```
in `config.yaml`. This leads to an error. The correct contents are
```
config:
  BinderHub:
    cors_allow_origin: '*'

jupyterhub:
  hub:
    config:
      BinderSpawner:
        cors_allow_origin: '*'
```

#### Expected behaviour
Adding the configuration as asked for in documentation should work. This happens using the second contents above.

#### Actual behaviour
Trying to run helm upgrade with the configuration as given in the documentation throws the error
```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
jupyterhub:
- (root): Additional property config is not allowed
```

### How to reproduce

1. Add `cors_allow_origin:yes` to `config.yaml` as stated in documentation.
2. Run helm upgrade

### Your personal set up

 - OS: arch linux, binderhub running in minikube.
 
 - Version(s): binderhub version `0.2.0-n735.h372efd3` from helm
