### ISSUE TITLE
Additional property auth is not allowed

### ISSUE THREAD

**Issue by sebastian-luna-valero** [jupyterhub/binderhub#1625]
### Bug description

Following the docs to add authentication to BinderHub: https://binderhub.readthedocs.io/en/latest/authentication.html

Using `values.yaml` with:

```yaml
config:
  BinderHub:
    auth_enabled: true

jupyterhub:
  cull:
    # don't cull authenticated users
    users: False
  hub:
    redirectToServer: false
    config:
      BinderSpawner:
        auth_enabled: true
    services:
      binder:
        oauth_client_id: service-binderhub
        oauth_no_confirm: true
        oauth_redirect_uri: "https://<binderhub_url>/oauth_callback"
    loadRoles:
      user:
        scopes:
          - self
          - "access:services"

  singleuser:
    # to make notebook servers aware of hub
    cmd: jupyterhub-singleuser

  auth: {}
```

#### Expected behaviour

It should deploy BinderHub.

#### Actual behaviour

Running:

```bash
sudo helm upgrade binderhub jupyterhub/binderhub --install --cleanup-on-fail --create-namespace --namespace binderhub --version 1.0.0-0.dev.git.3002.h5f189ce --values values.yaml
```

Returns:

```bash
jupyterhub:
- (root): Additional property auth is not allowed
```

### How to reproduce

Run:

```bash
sudo helm upgrade binderhub jupyterhub/binderhub --install --cleanup-on-fail --create-namespace --namespace binderhub --version 1.0.0-0.dev.git.3002.h5f189ce --values values.yaml
```

with:

```yaml

# [...]

jupyterhub:

# [...]

  auth: {}
```

### Your personal set up

 - OS: ubuntu 20.04
 
 - Version(s): k8s 1.23.11, helm v3.8.2, binderhub 1.0.0-0.dev.git.3002.h5f189ce
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
