### ISSUE TITLE
Question about docs for auth - what makes jupyterhub-singleuser cmd change required?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1854]
In this documentation about [enabling auth](https://binderhub.readthedocs.io/en/latest/authentication.html#enabling-authentication) it sais:

```yaml
  singleuser:
    # to make notebook servers aware of hub
    cmd: jupyterhub-singleuser
```

I'm wondering what makes this required? If it is, then the repo we build an image from requires jupyterhub as well - a requirement not presented otherwise for anonymous binderhub deployments like mybinder.org.
