### ISSUE TITLE
Support different container registry to push and pull

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/binderhub#1903]
### Proposed change

In some advanced use cases, the operator might want to push to one container registry and pull from another container registry. For example, the operator want to push to a public container registry like https://hub.docker.com/ and pull from a private [proxy cache](https://goharbor.io/docs/2.12.0/administration/configure-proxy-cache/).

![binderhub](https://github.com/user-attachments/assets/bddd4d1d-de0b-4c63-b336-3124ebf53798)

This will require

- [ ] Add extra option in Helm chart

    ```yaml
    config:
      BinderHub:
        use_registry: true
        image_prefix_to_push: "your-push-registry.io/<prefix>-"
        image_prefix_to_pull: "your-pull0registry.io/<prefix>-"
    ```

- [ ] Support new option when building container
- [ ] Support new option when contacting JupyterHub

### Who would use this feature?

@arnim and @rgaiacs want to use it at the mybinder.org server operated by GESIS.
