### ISSUE TITLE
AWS eks

### ISSUE THREAD

**Issue by rodentskie** [jupyterhub/binderhub#1931]
Hello, I've been trying do run the binderhub on AWS EKS. I've followed everything on the docs and have it deployed via helm. But the pods keeps restarting and error logs are not kinda helpful. 

What data you need from me or the .yaml files to help me assist on my issue?

### secret.yaml

```
registry:
  username: xxxx
  password: xxx
```

I'm using docker hub.

### config.yaml

```
service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  https:
    enabled: true
  hosts:
    - binderhub.xxxxyyyy.com

jupyterhub:
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
      - jupyterhub.xxxxyyyy.com

config:
  BinderHub:
    use_registry: true
    image_prefix: xxx/binder-pvt-
    # hub_url: http://k8s-jupyterh-proxypub-915fd97b45-3c878486236bc84a.elb.ap-southeast-2.amazonaws.com

```

I will uncomment `hub_url` once the `ALB` DNS name propagates with this command `kubectl --namespace=jupyterhub get svc proxy-public` then re-apply config.
