### ISSUE TITLE
Error creating user 403 Forbidden

### ISSUE THREAD

**Issue by paololazzari** [jupyterhub/binderhub#1942]
I have the following configuration for jupyterhub:

```
jupyterhub:
  proxy:
    service:
      type: ClusterIP
  hub:
    baseUrl: /jupyterhub/
    config:
      Authenticator:
        allow_all: true
```

but when I launch a repository I see the following error messages in the binder pod:

```
[I 250307 13:55:56 launcher:198] Creating user paololazzari-binder-redis-python-7htmqrbr for image us-central1-docker.pkg.dev/projectid/binderhub/binderpaololazzari-2dbinder-2dredis-2dpython-1412af:e57d3d790ec7495b39fe6c1167809dd67767f69c
[E 250307 13:55:56 launcher:208] Error creating user paololazzari-binder-redis-python-7htmqrbr: HTTP 403: Forbidden
    b'{"status": 403, "message": "Missing or invalid credentials."}'
```

and in the hub pod:

```
[W 2025-03-07 13:55:52.424 JupyterHub web:1873] 403 GET /jupyterhub/hub/api/users/paololazzari-binder-redis-python-2xgtfeyb (::ffff:10.92.0.79): Missing or invalid credentials.
[W 2025-03-07 13:55:52.425 JupyterHub log:192] 403 GET /jupyterhub/hub/api/users/paololazzari-binder-redis-python-2xgtfeyb (@::ffff:10.92.0.79) 1.66ms
```

why does it complain about credentials given I've set `allow_all: true` ?
