### ISSUE TITLE
AWS ECR registry for BinderHub deployment

### ISSUE THREAD

**Issue by nsriram13** [jupyterhub/binderhub#705]
I am trying to use ECR as the docker image registry for a BinderHub deployment. I was looking at the different settings in the helm chart and I am not sure how they map from the GCR examples provided in the docs to ECR. 

When explicitly pushing images to a registry, this is the command I use for ECR:
```
docker push 1234567890.dkr.ecr.region.amazonaws.com/repo:tag
```

How to translate this into the various components requested in the values file. Specifically the following in the values that are being set in `configmap.yaml`.
```
registry:
  enabled: true
  prefix: binderhub-local/
  host: https://gcr.io
  authHost:
  authTokenUrl: https://gcr.io/v2/token?service=gcr.io
  username: _json_key
  password:
```
For authentication, the nodes in our Kubernetes cluster are allowed to pull from ECR as they have IAM roles configured. Can I leave the authentication options blank here.

Really appreciate the guidance.
