### ISSUE TITLE
Proposal: Support specifying dependencies in a pyproject.toml (PEP-518)

### ISSUE THREAD

**Issue by funkyfuture** [jupyterhub/binderhub#846]
it'd be great to specify package dependencies in a `pyproject.toml` section, e.g.

```toml
[tool.binderhub.dependencies]
requests = "*"
scrapy = "<2"
```
