### ISSUE TITLE
Document how to ban repositories in binderhub

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#848]
In a [recent discourse thread]() someone asked how they could allow only one repository to run with binderhub. In answering, I realized that we don't document how to **ban** a repository. We should do so.

For reference, this is where we ban repos in mybinder.org:

https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml#L45

**Comment by sgibson91** [comment]
To allow access to only one repo, update the config with the following:
```
config:
  GitHubRepoProvider:
    banned_specs:
      - ^(?!org\/repo).*$ 
```
where `org` and `repo` are the ones you want to allow.
