### ISSUE TITLE
Jupyterhub customization on config.yaml

### ISSUE THREAD

**Issue by zxcGrace** [jupyterhub/binderhub#889]
I want to customize my JupyterHub and want to set the UI to be jupyterLab. I followed this [zero-to-binderhub](https://binderhub.readthedocs.io/en/latest/debug.html) to customize the jupyterhub, and I followed this [page](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html) to set the default environment of JupyterHub to JupyterLab. The config.yaml file I have for now looks like below:

```
config: 
  BinderHub: 
    use_registry: true
    image_prefix: grace55/binder-dev-
    hub_url: http://35.224.215.188
 
jupyterhub:
  singleuser:
    defaultUrl: "/lab"
  hub:
    extraConfig:
      jupyterlab: |
        c.Spawner.cmd = ['jupyter-labhub']
```
However, I still get the classic user interface instead of the JupyterLab interface. What is the correct format for customizing JupyterHub in BinderHub?
