### ISSUE TITLE
Hub pod stuck pending in bare metal kubernetes

### ISSUE THREAD

**Issue by zchef2k** [jupyterhub/binderhub#897]
I am trying to provision binderhub via helm to a bare metal Kubernetes cluster (Rancher/vSphere) but cannot get the hub pod to create. I have successfully followed the zero-to-jupyterhub tutorial and had to provide storageclass values in config.yaml to get its hub pod to provision with persistent storage. I suspect I need to do the same for binderhub, but it's not clear to me how to achieve that.

Most recent iteration is this, still unsuccessful....

```
config:
  BinderHub:
    use_registry: true
    image_prefix: <redacted>/binder-dev-
    hub_url: http://<redacted>
jupyterhub:
    extraConfig:
      hub:
        db:
          pvc:
            storageClassName: nfs-client
    singleuser:
      storage:
        dynamic:
          storageClass: nfs-client
```

Binderhub release 0.2.0-5ca42ec
Rancher 2.2.4 (kubernetes 1.13.5)

Any guidance is appreciated.

**Comment by bitnik** [comment]
BinderHub by default disables persistant storage (see `singleuser.storage.type`)

https://github.com/jupyterhub/binderhub/blob/01b1c59b9e7dc81250c1ed579c492ec2fd6baaf6/helm-chart/binderhub/values.yaml#L112-L117

> I suspect I need to do the same for binderhub

You don't need to if you setup classical BinderHub. Because it has no authentication and users (created on JupyterHub) are temporary.

**Comment by zchef2k** [comment]
I removed me singleuser bits and attempted to deploy again per the guide. But I'm not closer, obviously. The hub pod is stuck pending and there's a pvc pending, as well.



```
[me@here binderhub]$ kubectl get all --namespace bhub
NAME                           READY   STATUS    RESTARTS   AGE
pod/bhub-image-cleaner-bjgdt   1/1     Running   0          2m15s
pod/bhub-image-cleaner-lvctc   1/1     Running   0          2m15s
pod/bhub-image-cleaner-pt98x   1/1     Running   0          2m15s
pod/bhub-image-cleaner-sxh2v   1/1     Running   0          2m15s
pod/binder-5b8d47d987-frgb7    1/1     Running   0          2m15s
pod/hub-596b5fd59d-9z5dh       0/1     Pending   0          2m15s
pod/proxy-78686b8b44-b45zq     1/1     Running   0          2m15s

NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
service/binder         LoadBalancer   10.43.21.2      10.100.100.102   80:30732/TCP                 2m15s
service/hub            ClusterIP      10.43.224.199   <none>           8081/TCP                     2m15s
service/proxy-api      ClusterIP      10.43.194.157   <none>           8001/TCP                     2m15s
service/proxy-public   LoadBalancer   10.43.190.255   10.100.100.101   80:31301/TCP,443:31565/TCP   2m15s

NAME                                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/bhub-image-cleaner   4         4         4       4            4           <none>          2m15s

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/binder   1/1     1            1           2m15s
deployment.apps/hub      0/1     1            0           2m15s
deployment.apps/proxy    1/1     1            1           2m15s

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/binder-5b8d47d987   1         1         1       2m15s
replicaset.apps/hub-596b5fd59d      1         1         0       2m15s
replicaset.apps/proxy-78686b8b44    1         1         1       2m15s

NAME                                READY   AGE
statefulset.apps/user-placeholder   0/0     2m15s
```
```
[me@here binderhub]$ kubectl get pvc --namespace bhub
NAME         STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
hub-db-dir   Pending 
```

**Comment by bitnik** [comment]
I just see that your hub.db is in wrong place. Can you change it to (remove `extraConfig`)

```yaml
jupyterhub:
  hub:
    db:
      pvc:
        storageClassName: nfs-client
```
