### ISSUE TITLE
Add documentation for Docker Hub registry usage

### ISSUE THREAD

**Issue by nuest** [jupyterhub/binderhub#902]
I hope I'm not missing something, but I think the documentation for using the DockerHub registry is incomplete. Or is `docker login` all there is needed? I assume not, because I probably need to configure the org-option that is mentioned.

The tests in https://github.com/jupyterhub/binderhub/blob/master/binderhub/tests/test_registry.py use different options (token, usename/password).

Screenshot of https://binderhub.readthedocs.io/en/latest/setup-registry.html#set-up-docker-hub-registry where the "next section" is not what is promised :-)

![image](https://user-images.githubusercontent.com/1325054/61795900-b4fc4c80-ae24-11e9-8b13-f3807970855b.png)

**Comment by nuest** [comment]
Potentiall related to #205

**Comment by nuest** [comment]
Potentiall related to #205.

Configuration probably goes into https://github.com/jupyterhub/binderhub/blob/cc3db47b59258f427a59ccb001161d00c978095a/helm-chart/binderhub/values.yaml#L21

**Comment by bitnik** [comment]
These are the parts related to docker hub in the "next section":
- https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#if-you-are-using-docker-hub
- https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#id2

These settings are what we use in GESIS binder and should be enough to use docker hub registry.

secret.yaml:
```yaml
registry:
  username: <docker-id>
  password: <password>
```
config.yaml:
```yaml
config:
  BinderHub:
    use_registry: true
    image_prefix: <docker-id OR organization-name>/<prefix>-
```
