### ISSUE TITLE
GithubRepoProvider cannot access private repositories in Github

### ISSUE THREAD

**Issue by kaseyhackspace** [jupyterhub/binderhub#952]
I tried following the documentation on enabling private Github repository access but am unable to make it work. I am using the latest (to date) `0.2.0-fbbc302` helm chart for binderhub. My current secret.yaml looks like this:
``` yaml
config:
  GithubRepoProvider:
    access_token: <access-token-from-github>
```
But when I try to build a private repository I get the following:
``` bash
Could not resolve ref for gh:<username>/<repository>/master. Double check your URL.
```
Just to verify, I tried out the `GitLabRepoProvider` for gitlab with the following setting:
``` yaml
config:
  GitLabRepoProvider:
    private_token: <gitlab-token>
```
This pretty much works fine. Anything I am missing?

**P.S.** i also tried creating a Github App with a `client_id` and `client_secret` with the secret.yaml that looks like below but that also does not work.
``` yaml
config:
  GithubRepoProvider:
    client_id: <id>
    client_secret: <secret>
```
