### ISSUE TITLE
Add support for gitlab as build registry

### ISSUE THREAD

**Issue by rochaporto** [jupyterhub/binderhub#965]
We're trying to use a gitlab registry as backend for build images.

The setup is done using a helm chart, and passing in the configuration:
```yaml
config:
  DockerRegistry:
    token_url: "https://gitlab.cern.ch/jwt/auth"
    username: <username>
    password: <password>
  BinderHub:
    image_prefix: gitlab-registry.cern.ch/binder/images/build-
registry:
  url: "gitlab-registry.cern.ch"
```

After debugging the multiple authz errors, it seems to boil down to:
1. missing "service": "container_registry" when fetching a valid token using the token_url (this is [required by gitlab](https://docs.gitlab.com/ee/administration/packages/container_registry.html#enable-the-container-registry))
2. the build image name logic assumes a dockerhub like structure (up to two levels in the path). The gitlab registry allows more and we rely on this (see above with binder/images/actual-image-name)

I'll push a PR soon, just figuring out the best way to make 2. generic.
