### ISSUE TITLE
Local docker registry with self-signed certificate

### ISSUE THREAD

**Issue by ltetrel** [jupyterhub/binderhub#992]
Hello,

We are trying to set-up binderhub with our own docker registry in a local network as stated [here](https://discourse.jupyter.org/t/custom-local-docker-registry/2278).
We first tried with a http registry, the problem is that docker forces us to use https connection so it is not reliable.
So we tried to use https with a self-signed certificate, the issue is that binderhub just allows pulling from registry with a CA certificate.
There are two solutions :
1. Change [this line](https://github.com/jupyterhub/binderhub/blob/9fb6d3f97d68bd807d3996d54a67029977f9bba5/binderhub/registry.py#L212-L214) to allow
 for untrusted certificate with `validate_cert=False` => Fast and easy but maybe more insecure
2. Adding the self-signed certificate to `/etc/docker/certs.d` like [here](https://docs.docker.com/engine/security/certificates/) but should be inside the building pod, with proper mounting options => lot more "complicated" but secure

Do you have some ideas about this ?

ps: Using a public registry is not ideal for us since we sould need to buy a floating ip, a domain name, and it is far less optimal in term of pushing/pulling time (pull binderhub -> registry on local network VS pull binderhub -> DNS -> registry on public network)

Thanks,

**Comment by ltetrel** [comment]
*Yes sorry I meant `validate_cert = False`

So your suggestion is to use CA certificate from k8s ? Do you know how I could get it ?
For your second suggestion, would this be done when we spawn the instance for the first time ? Or can i do it now ?

Thanks for your quick reply :)

**Comment by ltetrel** [comment]
I found the k8s certificates, there are here but seems to be self-signed `/etc/kubernetes/pki/ca.crt`.
Your second suggestion seems to be feasible, I will try it and give feedbacks

**Comment by ltetrel** [comment]
So I struggled all day with this. I first configured the server to use [admission controller PodPreset](https://kubernetes.io/docs/concepts/workloads/pods/podpreset/#understanding-pod-presets), I had to :
1. add `- --runtime-config=settings.k8s.io/v1alpha1=true` to `/etc/kubernetes/manifests/kube-apiserver.yaml`
2. change `--enable-admission-plugins=NodeRestriction,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,PodPreset`
3. delete the pod running `kube-api-server` to rebuild it

After that I created and applied a podpreset with :
```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: certificates
spec:
  selector:
    matchLabels:
      component: binder
  volumeMounts:
    - mountPath: /etc/docker/certs.d/IP/
      name: docker-certs
    - mountPath: /usr/local/share/ca-certificates/
      name: ubuntu-certs
  volumes:
    - name: docker-certs
      hostPath:
        path: /certs
    - name: ubuntu-certs
      hostPath:
        path: /certs
```

And it is working with a test pod (with both `apply` or `create`), I see the volumes `*-certs` mounted:
```
apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    component: binder 
spec:
  containers:
    - name: website
      image: nginx
      ports:
        - containerPort: 80
```

However, it is not working with the binder pod. Even after deleting it..
```
metadata:
  annotations:
    checksum/config-map: 
    checksum/secret: 
  creationTimestamp: 
  generateName: 
  labels:
    app: binder
    component: binder
    heritage: Tiller
    name: binder
    pod-template-hash: 7bfc9b7484
    release: binderhub
```

Any ideas ?
